version: '3.7'

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      url: http://localhost:3000/
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
    volumes:
      - ./ghost-content:/var/lib/ghost/content

  db:
    image: mariadb:10.3.9-bionic
    container_name: ghost-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 3000:80
      - 4000:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/localhost:/etc/ssl/localhost
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot


  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  ghost-content:
  db-data:

